# Generated by Django 4.0.3 on 2022-07-11 10:14

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ffirstname1', models.CharField(max_length=200, null=True, verbose_name='First name')),
                ('Fmiddlename', models.CharField(max_length=200, null=True, verbose_name='Middle name')),
                ('Flastname', models.CharField(max_length=200, null=True, verbose_name='Last name')),
                ('Femployeenum', models.CharField(max_length=200, null=True, verbose_name='Employee Number')),
                ('Fdaterequest', models.DateTimeField(auto_now_add=True, null=True)),
                ('Fimagee', models.ImageField(max_length=254, upload_to='')),
                ('Fgsis', models.CharField(max_length=200, null=True, verbose_name='GSIS')),
                ('Fgsisno', models.CharField(max_length=200, null=True, verbose_name='GSIS NO')),
                ('Ftin', models.CharField(max_length=200, null=True, verbose_name='TIN')),
                ('Fpagibig', models.CharField(max_length=200, null=True, verbose_name='PAG-IBIG')),
                ('Fphilhealth', models.CharField(max_length=200, null=True, verbose_name='Philhealth')),
                ('Fothers', models.CharField(max_length=200, null=True, verbose_name='Others')),
                ('Fconterpersonn', models.CharField(max_length=200, null=True, verbose_name='Contactperson')),
                ('Fcontactnum', models.CharField(max_length=200, null=True, verbose_name='Contactnumber')),
                ('Faddress', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('Fsignature', models.ImageField(max_length=200, null=True, upload_to='', verbose_name='Signature')),
                ('femail', models.CharField(max_length=200, null=True, verbose_name='Faculty Email')),
                ('fstatus', models.CharField(default='P', max_length=200, null=True, verbose_name='fstatus')),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname1', models.CharField(max_length=200, null=True, verbose_name='First name')),
                ('middlename', models.CharField(max_length=200, null=True, verbose_name='Middle name')),
                ('lastname', models.CharField(max_length=200, null=True, verbose_name='Last name')),
                ('course', models.CharField(choices=[('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology'), ('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology'), ('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology'), ('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology'), ('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology'), ('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology'), ('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology'), ('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology'), ('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology'), ('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology'), ('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology'), ('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology'), ('BET- CoET', 'Bachelor of Engineering Technology Major in Computer Engineering Technology')], max_length=200)),
                ('daterequest', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagee', models.ImageField(max_length=254, upload_to='')),
                ('conterpersonn', models.CharField(max_length=200, null=True, verbose_name='Contactperson')),
                ('contactnum', models.CharField(max_length=200, null=True, verbose_name='Contactnumber')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('studnum', models.CharField(max_length=200, null=True, verbose_name='Student Number')),
                ('signature', models.ImageField(max_length=200, null=True, upload_to='', verbose_name='Signature')),
                ('semail', models.CharField(max_length=200, null=True, verbose_name='Student Email')),
                ('status', models.CharField(default='P', max_length=200, null=True, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='Useraccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Usertype', models.CharField(choices=[('A', 'Admin'), ('S', 'Student'), ('F', 'Faculty')], default='S', max_length=10, verbose_name='Usertype')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
